version: '2'
services:

  app:
    build: .
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: