version: '2'
services:

  app:
    build: .
    ports:
      - "8000:8000"
    command: python app.py 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: